[package]
name = "pictas-interface-rs"
version = "0.1.0"
authors = ["bigbass1997 <bigbass1997.website@gmail.com>"]
edition = "2021"

[dependencies]
serialport = "4.0"
strum = "0.24"
strum_macros = "0.24"
clap = "3.1"
tasd-edit = { git = "https://github.com/bigbass1997/TASD-Edit" }